# base image elixer to start with
FROM elixir:1.6.4

# install hex package manager
RUN mix local.hex --force \
    && mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
  && apt-get install -y nodejs


# create app folder
RUN mkdir /app
COPY . /app
WORKDIR /app

RUN mix deps.get \
    && mix local.rebar --force

WORKDIR /app/assets
RUN npm install

WORKDIR /app

# install dependencies
# run phoenix in *dev* mode on port 4000
CMD ["mix", "phx.server"]
