version: '3.3'
services:
  phoenix:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules
      - phoenix_deps:/app/deps
volumes:
  node_modules:
  phoenix_deps:
